### ISSUE TITLE
Section 02_01 - can you please solve readInData.py

### ISSUE THREAD

**Issue by tcd1558** [tcd1558/ScriptingForTesters#2]
This is the second problem. I am creating this early, so there is more than 1 problem for this project.

**Comment by tcd1558** [comment]
Please solve the readInData.py problem.

**Comment by tcd1558** [comment]
Issue is to be solved in a clone of the main tree and then open a pull request to merge it back into the main tree.

**Comment by tcd1558g** [comment]
I have fixed issue #2 in the branch main_2. Please review. Thx.

**Comment by tcd1558** [comment]
The solution for 02_04 has been merged into the main tree.

**Comment by tcd1558** [comment]
Closed
