### ISSUE TITLE
02_03 - Google Chart API - please provide a solution

### ISSUE THREAD

**Issue by tcd1558** [tcd1558/ScriptingForTesters#7]
Exercise 02_03 creates a chart from a csv file with tests, number of assertions, and number of fails. Please create a solution. The problem needs to be solved in the main tree.

**Comment by tcd1558g** [comment]
The issue has been fixed and has been committed to the tree main_2. Can somebody review the changes? Thx.

**Comment by tcd1558** [comment]
Merge completed.
